src/Entity/TimeConstraint.php
<?php

namespace App\Entity;

use App\Repository\ConstraintRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ConstraintRepository::class)
 * @ORM\Table(name="constraints")
 * @UniqueEntity("name")
 */
class TimeConstraint
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $name;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class)
     * @ORM\JoinTable(name="constraint_tag")
     */
    private $exclusions;

    /**
     * @ORM\Column(type="date_immutable")
     */
    private $begin_date;

    /**
     * @ORM\Column(type="date_immutable")
     */
    private $end_date;

    /**
     * @ORM\Column(type="json")
     */
    private $schedule = [];

    public function __construct()
    {
        $this->exclusions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getExclusions(): Collection
    {
        return $this->exclusions;
    }

    public function addExclusion(Tag $exclusion): self
    {
        if (!$this->exclusions->contains($exclusion)) {
            $this->exclusions[] = $exclusion;
        }

        return $this;
    }

    public function removeExclusion(Tag $exclusion): self
    {
        $this->exclusions->removeElement($exclusion);

        return $this;
    }

    public function getBeginDate(): ?DateTimeImmutable
    {
        return $this->begin_date;
    }

    public function setBeginDate(DateTimeImmutable $begin_date): self
    {
        $this->begin_date = $begin_date;

        return $this;
    }

    public function getEndDate(): ?DateTimeImmutable
    {
        return $this->end_date;
    }

    public function setEndDate(DateTimeImmutable $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getSchedule(): ?array
    {
        return $this->schedule;
    }

    public function setSchedule(array $schedule): self
    {
        $this->schedule = $schedule;

        return $this;
    }
}

src/Controller/ConstraintController.php
<?php

namespace App\Controller;

use App\Entity\TimeConstraint;
use App\Form\TimeConstraintType;
use App\Repository\ConstraintRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Validator\Constraints\Positive;

/**
 * @Route("/constraint")
 */
class ConstraintController extends AbstractController
{
    /**
     * @Route("/{param}", name="constraint_index", requirements={"param"="clear"})
     */
    public function index(string $param = null, ConstraintRepository $cstrRepo): Response
    {
        if ('clear' === $param) {
            $cstrRepo->removeExpired();

            return $this->redirectToRoute('constraint_index');
        }

        return $this->render('constraint/index.html.twig', [
            'time_constraints' => $cstrRepo->findAll(),
        ]);
    }

    /**
     * @Route("/add", name="constraint_add")
     */
    public function add(Request $request): Response
    {
        $timeCstr = new TimeConstraint();
        $form = $this->createForm(TimeConstraintType::class, $timeCstr);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($timeCstr);
            $em->flush();

            return $this->redirectToRoute('constraint_index');
        }

        return $this->render('constraint/add.html.twig', [
            'time_cstr' => $timeCstr,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit/{id}", name="constraint_edit")
     */
    public function edit(Request $request, TimeConstraint $timeCstr): Response
    {
        $form = $this->createForm(TimeConstraintType::class, $timeCstr);
        $form->handleRequest($request);
        $willBeDeleted = 'delete' === $request->get('delete');

        if ($form->isSubmitted() && ($form->isValid() || $willBeDeleted)) {
            $em = $this->getDoctrine()->getManager();
            if ($willBeDeleted) {
                $em->remove($timeCstr);
            }
            $em->flush();

            return $this->redirectToRoute('constraint_index');
        }

        return $this->render('constraint/edit.html.twig', [
            'time_cstr' => $timeCstr,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/reservation", name="constraint_reservation")
     */
    public function reservation(Request $request, ConstraintRepository $cstrRepo): Response
    {
        $builder = $this->createFormBuilder();
        $rsvnLimits = $cstrRepo->getReservationLimits();
        foreach ($rsvnLimits as $key => $value) {
            $builder->add($key, IntegerType::class, [
                'label' => $key,
                'data' => $value,
                'constraints' => [
                    new Positive(),
                ],
            ]);
        }
        $form = $builder->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cstrRepo->setReservationLimits($form->getData());
        }

        return $this->render('constraint/reservation.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/constraint/add.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Dodawanie ograniczenia' %}
{% block main %}

  <h2 class="main-title">{{ 'bx bx-add-to-queue'|ico }}{{ main_title|trans }}</h2>

  {{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.begin_date) }}
    {{ form_row(form.end_date) }}
    {{ form_row(form.schedule) }}
    {{ form_row(form.exclusions, {attr: {class: 'jqslct2-multiple-select'}}) }}
    <script>
      $('select.jqslct2-multiple-select').select2({
        width: '99%',
      });
    </script>
    <p class="form-group button-row">
      <a class="button" href="{{ path('constraint_index') }}">
        {{ 'bx bx-arrow-back'|ico }}{{ 'Anuluj'|trans }}
      </a>
      <button type="submit">
        {{ 'bx bx-plus'|ico }}{{ 'Dodaj'|trans }}
      </button>
    </p>
  {{ form_end(form) }}

{% endblock %}

templates/constraint/edit.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Edycja ograniczenia' %}
{% block main %}

  <h2 class="main-title">{{ 'bx bx-edit'|ico }}{{ main_title|trans }}</h2>

  {{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_row(form.name) }}
    {{ form_row(form.begin_date) }}
    {{ form_row(form.end_date) }}
    {{ form_row(form.schedule) }}
    {{ form_row(form.exclusions, {attr: {class: 'jqslct2-multiple-select'}}) }}
    <script>
      $('select.jqslct2-multiple-select').select2({
        width: '99%',
      });
    </script>
    <p class="form-group button-row">
      <a class="button" href="{{ path('constraint_index') }}">
        {{ 'bx bx-arrow-back'|ico }}{{ 'Anuluj'|trans }}
      </a>
      <button type="submit" name="save" value="save" class="enable-on-change">
        {{ 'bx bx-save'|ico }}{{ 'Zapisz'|trans }}
      </button>
      <button type="submit" name="delete" value="delete"
        onclick="return confirm('{{ 'Czy na pewno chcesz usunąć ograniczenie?'|trans }}')">
        {{ 'bx bx-trash'|ico }}{{ 'Usuń'|trans }}
      </button>
    </p>
  {{ form_end(form) }}

{% endblock %}

templates/constraint/index.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Ograniczenia czasu' %}
{% block main %}

  <h2 class="main-title">{{ 'bx bx-time'|ico }}{{ main_title|trans }}</h2>

  <div class="list-table">
    <table>
      <thead>
        <tr>
          <th>{{ 'Nazwa'|trans }}</th>
          <th>{{ 'Początek'|trans }}</th>
          <th>{{ 'Koniec'|trans }}</th>
          <th>{{ 'Harm.'|trans }}</th>
        </tr>
      </thead>
      <tbody>
      {% for cstr in time_constraints %}
        <tr>
          <td><a href="{{ path('constraint_edit', {id: cstr.id}) }}">{{ cstr.name }}</a></td>
          <td>{{ cstr.beginDate ? cstr.beginDate|date('d.m.Y') : '' }}</td>
          <td>{{ cstr.endDate ? cstr.endDate|date('d.m.Y') : '' }}</td>
          <td>{{ cstr.schedule ? '✔' : '' }}</td>
        </tr>
      {% else %}
        <tr>
          <td colspan="4">{% trans %}Nie znaleziono ograniczeń{% endtrans %}.</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="form-group button-row">
    <a class="button" href="{{ path('constraint_add') }}">
      {{ 'bx bx-plus'|ico }}{{ 'Dodaj'|trans }}
    </a>
    <a class="button" href="{{ path('constraint_index', {param: 'clear'}) }}">
      {{ 'bx bx-trash'|ico }}{{ 'Usuń nieaktualne'|trans }}
    </a>
    <a class="button" href="{{ path('constraint_reservation') }}">
      {{ 'bx bx-cog'|ico }}{{ 'Limity rezerwacji'|trans }}
    </a>
  </div>

{% endblock %}

templates/constraint/reservation.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Limity rezerwacji' %}
{% block main %}

  <h2 class="main-title">{{ 'bx bx-cog'|ico }}{{ main_title|trans }}</h2>

  {{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_widget(form) }}
    <div class="form-group button-row">
      <a class="button" href="{{ path('constraint_index') }}">
        {{ 'bx bx-arrow-back'|ico }}{{ 'Anuluj'|trans }}
      </a>
      <button type="submit" name="save" value="save" class="enable-on-change">
        {{ 'bx bx-save'|ico }}{{ 'Zapisz'|trans }}
      </button>
    </div>
  {{ form_end(form) }}

{% endblock %}