src/Entity/Request.php
<?php

namespace App\Entity;

use App\Repository\RequestRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RequestRepository::class)
 * @ORM\Table(name="requests")
 */
class Request
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $requester;

    /**
     * @ORM\ManyToOne(targetEntity=Room::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $room;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $begin_time;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $end_time;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $create_time;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $details;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $error;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $reservation_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRequester(): ?User
    {
        return $this->requester;
    }

    public function setRequester(User $requester): self
    {
        $this->requester = $requester;

        return $this;
    }

    public function getRoom(): ?Room
    {
        return $this->room;
    }

    public function setRoom(?Room $room): self
    {
        $this->room = $room;

        return $this;
    }

    public function getBeginTime(): ?\DateTimeImmutable
    {
        return $this->begin_time;
    }

    public function setBeginTime(\DateTimeImmutable $begin_time): self
    {
        $this->begin_time = $begin_time;

        return $this;
    }

    public function getEndTime(): ?\DateTimeImmutable
    {
        return $this->end_time;
    }

    public function setEndTime(\DateTimeImmutable $end_time): self
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getCreateTime(): ?\DateTimeImmutable
    {
        return $this->create_time;
    }

    public function setCreateTime(\DateTimeImmutable $create_time): self
    {
        $this->create_time = $create_time;

        return $this;
    }

    public function getDetails(): ?string
    {
        return $this->details;
    }

    public function setDetails(?string $details): self
    {
        $this->details = $details;

        return $this;
    }

    public function getError(): ?string
    {
        return $this->error;
    }

    public function setError(string $error): self
    {
        $this->error = $error;

        return $this;
    }

    public function getReservationId(): ?int
    {
        return $this->reservation_id;
    }

    public function setReservationId(?int $reservation_id): self
    {
        $this->reservation_id = $reservation_id;

        return $this;
    }
}

src/Controller/RequestController.php
<?php

namespace App\Controller;

use App\CustomTypes\UserLevel;
use App\Entity\Request as EntityRequest;
use App\Entity\Reservation;
use App\Repository\RequestRepository;
use App\Service\AppMailer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/request")
 */
class RequestController extends AbstractController
{
    private const MAX_RQST_COUNT = 3;

    /**
     * @Route("/", name="request_index")
     */
    public function index(RequestRepository $rqstRepo): Response
    {
        $requests = [];
        if ($this->isGranted(UserLevel::ADMIN)) {
            $requests = $rqstRepo->findBy([], ['create_time' => 'ASC', 'room' => 'ASC']);
        } else {
            $requests = $rqstRepo->findBy(['requester' => $this->getUser()->getId()]);
        }

        return $this->render('request/index.html.twig', ['requests' => $requests]);
    }

    /**
     * @Route("/delete/{id}", name="request_delete")
     */
    public function delete(EntityRequest $rqst, Request $request, AppMailer $mailer): Response
    {
        if (
            $this->canEditRequest($rqst)
            && $this->isCsrfTokenValid('request_delete', $request->request->get('token'))
        ) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($rqst);
            $em->flush();
            if ($this->getUser() !== $rqst->getRequester()) {
                $mailer->notify('Odrzucenie wniosku o rezerwację', 'Twój wniosek o rezerwację sali'.
                    ' %rqst_room% w dniu %rqst_date% został odrzucony przez %user%.', null, $rqst);
            }

            return $this->redirectToRoute('request_index');
        }

        throw $this->createAccessDeniedException();
    }

    public function add(
        Reservation $rsvn,
        string $rsvnError,
        RequestRepository $repo,
        AppMailer $mailer
    ): Response {
        if ($repo->getUserRequestsCount($rsvn->getEditor()) >= static::MAX_RQST_COUNT) {
            return $this->render('main/redirect.html.twig', [
                'path' => 'request_index',
                'main_content' => 'Przekroczono limit nierozpatrzonych wniosków o rezerwację sali.',
            ]);
        }
        $rqst = new EntityRequest();
        $rqst->setRequester($rsvn->getRequester());
        $rqst->setRoom($rsvn->getRoom());
        $rqst->setCreateTime($rsvn->getEditTime());
        $rqst->setBeginTime($rsvn->getBeginTime());
        $rqst->setEndTime($rsvn->getEndTime());
        $rqst->setDetails($rsvn->getDetails());
        $rqst->setError($rsvnError);
        
        $em = $this->getDoctrine()->getManager();
        if ($rsvn->getId()) {
            $rqst->setReservationId($rsvn->getId());
            $em->refresh($rsvn);
        }
        $em->persist($rqst);
        $em->flush();
        if ($this->getUser() !== $rqst->getRequester()) {
            $mailer->notify('Złożenie wniosku o rezerwację', '%user% złożył(a) w Twoim imieniu '.
                'wniosek o rezerwację sali %rqst_room% w dniu %rqst_date%.', null, $rqst);
        }

        return $this->redirectToRoute('request_index');
    }

    private function canEditRequest(EntityRequest $rqst): bool
    {
        if ($this->getUser() === $rqst->getRequester()) {
            return true;
        }

        return $this->isGranted(UserLevel::ADMIN);
    }
}

templates/request/index.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Wnioski o rezerwację' %}
{% block main %}

	<h2 class="main-title">{{ 'bx bx-file'|ico }}{{ main_title|trans }}</h2>

  <style>
	  .list-table > table, .slide-button + tr > td { width: 100%; }
    .right-float-panel { float: right; margin: 0 0 0.5em 0; }
		.right-float-panel .button { margin: 0 0 0 0.5em; }
		.slide-button { cursor: pointer; }
		.slide-button:hover, .slide-button.open { color: #2d2dc5; }
		.list-table .slide-cell { padding: 0 0.5em; }
		.slide-content > p { margin: 0 0 0.5em 0; }
	</style>
	<div class="list-table">
		<table>
			<thead>
				<tr>
          <th>{{ 'Użytkownik'|trans }}</th>
					<th>{{ 'Sala'|trans }}</th>
					<th>{{ 'Termin'|trans }}</th>
				</tr>
			</thead>
			<tbody>
				{% for rqst in requests %}
					<tr class="slide-button">
						<td>{{ rqst.requester.fullname }}</td>
						<td>{{ rqst.room.title }}</td>
						<td>{{ rqst.beginTime|date('d.m.Y H:i') }}-{{ rqst.endTime|date('H:i') }}</td>
					</tr>
					<tr>
						<td colspan="3" class="slide-cell">
							<div class="slide-content">
								<div class="form-group button-row right-float-panel">
									{% if is_granted(constant('App\\CustomTypes\\UserLevel::ADMIN')) %}
										<a class="button" href="{{ path('reservation_request', {id: rqst.id}) }}">
											{{ 'bx bx-calendar-check'|ico }}{{ 'Akceptuj'|trans }}
										</a>
									{% endif %}
									<form action="{{ path('request_delete', {id: rqst.id}) }}" method="post">
										<input type="hidden" name="token" value="{{ csrf_token('request_delete') }}"/>
										<button type="submit" class="button" 
											onclick="return confirm('{{ 'Czy na pewno chcesz odrzucić wniosek?'|trans }}')">
											{{ 'bx bx-trash'|ico }}{{ 'Odrzuć'|trans }}
										</button>
									</form>
								</div>
								<p><b>{{ 'Powód'|trans }}:</b> {{ rqst.error|rsvn_err_val }}</p>
								<p><b>{{ 'Uzasadnienie'|trans }}:</b> {{ rqst.details }}</p>
							</div>
						</td>
					</tr>
				{% else %}
					<tr>
						<td colspan="3">{% trans %}Nie znaleziono wniosków{% endtrans %}.</td>
					</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<script>
	  $('.slide-content').hide();
		$('.slide-button').click(function() {
			$(this).toggleClass('open');
			$(this).next().find('.slide-content').slideToggle('fast');
		});
	</script>

{% endblock %}