src/Entity/User.php
<?php

namespace App\Entity;

use App\CustomTypes\Lang;
use App\CustomTypes\UserLevel;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\Table(name="users")
 * @UniqueEntity("email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fullname;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=2)
     */
    private $lang = Lang::PL;

    /**
     * @ORM\Column(type="string", length=32)
     */
    private $access;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, mappedBy="users")
     */
    private $tags;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $last_login;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->email;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFullname(): ?string
    {
        return $this->fullname;
    }

    public function getTitle()
    {
        return "{$this->fullname} <{$this->email}>";
    }

    public function setFullname(string $fullname): self
    {
        $this->fullname = trim(preg_replace('/\s+/', ' ', $fullname));

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getLang(): string
    {
        return $this->lang;
    }

    public function setLang(string $lang): self
    {
        $this->lang = $lang;

        return $this;
    }

    public function getAccess(): ?string
    {
        return $this->access;
    }

    public function setAccess(string $access): self
    {
        $this->access = UserLevel::valid($access);

        return $this;
    }

    public function getAccessLevel(): int
    {
        return UserLevel::getIndex($this->access);
    }

    public function getAccessName(): string
    {
        return UserLevel::getValue($this->access);
    }

    public function getRoles(): ?array
    {
        $roles = $this->roles;
        $roles[] = $this->access;
        $roles[] = UserLevel::USER;

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
            $tag->addUser($this);
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->removeElement($tag)) {
            $tag->removeUser($this);
        }

        return $this;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getPassword()
    {
        // for "remember me" cookie hash
        return $this->fullname;
    }

    public function getSalt()
    {
        return null;
    }

    public function eraseCredentials()
    {
        return null;
    }

    public function getLastLogin(): ?\DateTimeImmutable
    {
        return $this->last_login;
    }

    public function setLastLogin(\DateTimeImmutable $last_login): self
    {
        $this->last_login = $last_login;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\CustomTypes\UserLevel;
use App\Entity\User;
use App\Service\AppHelper;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

class UserType extends AbstractType
{
    private $user = [];

    public function __construct(Security $security)
    {
        $user = AppHelper::USR($security);
        $this->user['self'] = ['id' => $user->getId(), 'level' => $user->getAccessLevel()];
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        /** @var User */
        $user = $builder->getData();
        $this->user['origin'] = ['id' => $user->getId(), 'level' => $user->getAccessLevel()];

        $builder->add('fullname', TextType::class, [
            'label' => 'Nazwa wyświetlana',
            'constraints' => [new Length(['min' => 3])],
        ]);
        if ($options['admin_edit']) {
            $selfLevel = $this->user['self']['level'];
            $builder->add('access', ChoiceType::class, [
                'choices' => $options['access_names'],
                'label' => 'Typ konta',
                'expanded' => false,
                'multiple' => false,
            ])->add('tags', null, [
                'by_reference' => false,
                'label' => 'Etykiety',
                'choice_filter' => function ($tag) use ($selfLevel) {
                    return $tag->getLevel() < $selfLevel;
                },
            ]);
        }
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
            'admin_edit' => false,
            'access_names' => [],
            'constraints' => [new Assert\Callback([$this, 'validateUserLevel'])],
        ]);
    }

    public function validateUserLevel(User $modifiedUser, ExecutionContextInterface $context)
    {
        if ($this->user['self']['id'] !== $this->user['origin']['id']) {
            if (
                $this->user['self']['level'] < UserLevel::getIndex(UserLevel::ADMIN)
                || $this->user['self']['level'] < $this->user['origin']['level']
            ) {
                return $context->buildViolation('Nie masz uprawnień do edycji tego użytkownika.')
                    ->addViolation()
                ;
            }
        }
        if ($this->user['self']['level'] < $modifiedUser->getAccessLevel()) {
            $context->buildViolation('Nie możesz ustawić tej wartości.')
                ->atPath('access')->addViolation();
        }
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\CustomTypes\Lang;
use App\CustomTypes\UserLevel;
use App\Entity\User;
use App\Form\UserToEmailTransformer;
use App\Form\UserType;
use App\Repository\UserRepository;
use App\Service\AppHelper;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/user")
 */
class UserController extends AbstractController
{
    /**
     * @Route("/", name="user_index")
     */
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('user/index.html.twig', ['users' => $userRepository->findAll()]);
    }

    /**
     * @Route("/self", name="user_self")
     */
    public function selfShow(): Response
    {
        return $this->forward('App\\Controller\\UserController::show', ['self' => true]);
    }

    /**
     * @Route("/show", name="user_form_show")
     * @Route("/show/{id}", name="user_show")
     */
    public function show(
        User $user = null,
        bool $self = false,
        Request $request,
        UserToEmailTransformer $userToEmail,
        UserRepository $userRepo
    ): Response {
        $session = AppHelper::initSession($request);
        $builder = $this->createFormBuilder(null, ['csrf_protection' => false]);
        $builder->setAction($this->generateUrl('user_form_show'))->setMethod('GET')
            ->add('user', TextType::class, [
                'data_class' => null,
                'data' => $user,
                'label' => 'Pełna nazwa',
            ])
        ;
        $builder->get('user')->addModelTransformer($userToEmail);
        $form = $builder->getForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData()['user'];
            $session->set('last_user_id', $user->getId());
        }
        if (!$form->isSubmitted() && !$user) {
            if (!$self && null !== ($lastUserId = $session->get('last_user_id'))) {
                $user = $userRepo->find($lastUserId);
            } else {
                $user = $this->getUser();
            }
            AppHelper::updateForm($form, 'user', TextType::class, ['data' => $user]);
        }

        return $this->render('user/show.html.twig', [
            'user' => $user,
            'lang' => Lang::getValue($user->getLang()),
            'can_edit_user' => $this->canEditUser($user),
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/edit", name="user_self_edit")
     * @Route("/edit/{id}", name="user_edit")
     */
    public function edit(User $user = null, Request $request): Response
    {
        $user = $user ?? $this->getUser();
        if (!$this->canEditUser($user)) {
            throw $this->createAccessDeniedException();
        }
        $unauthorizedTags = AppHelper::getUnauthorizedTags($this->getUser(), $user->getTags());
        $formOptions = [];
        $formOptions['admin_edit'] = $this->isGranted(UserLevel::ADMIN);
        $formOptions['access_names'] = array_flip(UserLevel::getValues());
        array_splice($formOptions['access_names'], $this->getUser()->getAccessLevel() + 1);
        $form = $this->createForm(UserType::class, $user, $formOptions);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            array_walk($unauthorizedTags, [$user, 'addTag']);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('user_show', ['id' => $user->getId()]);
        }

        return $this->render('user/edit.html.twig', [
            'user' => $user,
            'form' => $form->createView(),
        ]);
    }

    private function canEditUser(User $user): bool
    {
        if ($this->getUser() === $user) {
            return true;
        }
        if ($this->isGranted(UserLevel::ADMIN)) {
            return $this->getUser()->getAccessLevel() > $user->getAccessLevel();
        }

        return false;
    }
}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Edycja użytkownika' %}
{% block main %}

  <h2 class="main-title">{{ 'bx bx-edit'|ico }}{{ main_title|trans }}</h2>
  {{ form_start(form) }}
    {{ form_errors(form) }}
    {{ form_row(form.fullname) }}
    {% if form.access is defined %}
      {{ form_row(form.access, {attr: {class: 'jqslct2-single-select'}}) }}
      <script>
        $('select.jqslct2-single-select').select2({
          minimumResultsForSearch: Infinity, 
          width: '10em',
        });
      </script>
    {% endif %}
    {% if form.tags is defined %}
      {{ form_row(form.tags, {attr: {class: 'jqslct2-multiple-select'}}) }}
      <script>
        $('select.jqslct2-multiple-select').select2({
          width: '99%',
        });
      </script>
    {% endif %}
    <div class="form-group button-row">
      <a class="button" href="{{ path('user_show', {id: user.id}) }}">
        {{ 'bx bx-arrow-back'|ico }}{{ 'Anuluj'|trans }}
      </a>
      <button type="submit" name="save" value="save" class="enable-on-change">
        {{ 'bx bx-save'|ico }}{{ 'Zapisz'|trans }}
      </button>
    </div>
  {{ form_end(form) }}
  
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Lista użytkowników' %}
{% block main %}

  <h2 class="main-title">{{ main_title|trans }}</h2>
  <ul>
  {% for user in users %}
    <li>
      <a href="{{ path('user_show', {'id': user.id}) }}">{{ user.fullname }}</a>
    </li>
  {% endfor %}
  </ul>
  
{% endblock %}

templates/user/show.html.twig
{% extends 'base.html.twig' %}
{% set main_title = 'Profil użytkownika' %}
{% block main %}

  <h2 class="main-title">{{ 'bx bx-id-card'|ico }}{{ main_title|trans }}</h2>

  {{ form_start(form) }}
    <div class="form-group">
      {{ form_label(form.user) }}
      {{ form_errors(form.user) }}
      {{ form_widget(form.user, {'attr': {
        class: 'jqslct2-single-user submit-on-change', 'data-text': user.fullname,
      }}) }}
      <button type="submit" class="hide-on-load">{{ 'bx bx-refresh'|ico }}OK</button>
    </div>
    {{ include('jqslct2-single-user.html.twig') }}
  {{ form_end(form) }}

  <p>
    {{ 'Typ konta'|trans }}: 
    <span class="p-sub">
      {{ user.accessname|trans }}
    </span>
  </p>
  <p>
    {{ 'Adres e-mail'|trans }}: 
    <span class="p-sub">
      <a href="mailto:{{ user.email }}">{{ user.email }}</a>
    </span>
  </p>
  <div class="tag-list">
    {{ 'Nadane etykiety'|trans }}:
    <ul>
    {% for tag in user.tags %}
      <li>{{ tag|trans }}</li>
    {% else %}
      <li>{{ 'żadne'|trans }}</li>
    {% endfor %}
    </ul>
  </div>
  <p>
    {{ 'Ostatnie logowanie'|trans }}: 
    <span class="p-sub">
      {{ app.request.locale|icu_date(user.lastLogin) }}
    </span>
  </p>
  <p>
    {{ 'Wybrany język'|trans }}: 
    <span class="p-sub">
      {{ lang|trans }}
    </span>
  </p>

  <p class="form-group button-row">
    {% if can_edit_user %}
      <a class="button" href="{{ path('user_edit', {id: user.id}) }}">
        {{ 'bx bx-edit'|ico }}{{ 'Edytuj profil'|trans }}
      </a>
    {% endif %}
    <a class="button" href="{{ path('rsvn_view_user', {id: user.id}) }}">
      {{ 'bx bx-calendar-week'|ico }}{{ 'Rezerwacje'|trans }}
    </a>
    {% if is_granted('IS_IMPERSONATOR') %}
      {% if app.user.id == user.id %}
        <a class="button" href="{{ path('main', {_switch_user: '_exit'}) }}">
          {{ 'bx bx-user'|ico }}{{ 'Porzuć tożsamość'|trans }}
        </a> 
      {% endif %}
    {% else %}
      {% if is_granted('ROLE_ALLOWED_TO_SWITCH') and app.user.id != user.id %}
        <a class="button" href="{{ path('main', {_switch_user: user.email}) }}">
          {{ 'bx bx-user'|ico }}{{ 'Przyjmij tożsamość'|trans }}
        </a> 
      {% endif %}
    {% endif %}
  </p>

{% endblock %}